### ISSUE TITLE
Automatisation du Rapport Jest - Pipeline

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#33] opened 2023-10-04 21:36 UTC
Voir issue : https://github.com/orgs/Monitoring-Mtl/projects/1/views/2?pane=issue&itemId=40640579

**Comment by lamiphil** [comment] 2023-10-20 16:33
This issue was a duplicate of issue : https://github.com/orgs/Monitoring-Mtl/projects/1/views/1?pane=issue&itemId=40527344
Closing this issue because the original was closed.

**Closed as completed by lamiphil** 2023-10-20 16:33 UTC
Labels: devOps
